name: My First Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: run lint
      working-directory: starter/frontend
      run: |
          npm ci
          npm run lint

  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: run test
      working-directory: starter/frontend
      run: |
          npm ci
          npm run test

# Post-build job that depends on the completion of the previous two jobs
  post-build-actions:
    # Specifies that this job depends on the completion of 'lint' and 'test'
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: build
      working-directory: starter/frontend
      run: |
          npm ci
          npm run test
